### ISSUE TITLE
Error with mybatis-plus dynamic datasource dynamic-datasource-spring-boot-starter

### ISSUE THREAD

**Issue by futurOR** [taosdata/TDengine#10323]
**Bug Description**

POM
```
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>
```
application.yml
```
dynamic:
      primary: master
      datasource:
              master:
                url: jdbc:mysql://ip:port/database?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true&useSSL=false
                username: root
                password: ***
                driver-class-name: com.mysql.cj.jdbc.Driver
              taos:
                driver-class-name: com.taosdata.jdbc.TSDBDriver
                url: jdbc:TAOS://192.168.1.211:6030/mp_test?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
                user: 
                password: 
```

2022-02-19 11:01:02.636 [main] INFO  com.alibaba.druid.pool.DruidDataSource:994 - {dataSource-7,master} inited
2022-02-19 11:01:02.639 [main] ERROR com.alibaba.druid.pool.DruidDataSource:974 - {dataSource-8} init error
java.lang.IllegalStateException: dbType not support : null, url jdbc:TAOS://localhost:6030/mp_test?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
	at com.alibaba.druid.wall.WallFilter.init(WallFilter.java:166)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:839)
	at com.baomidou.dynamic.datasource.creator.DruidDataSourceCreator.createDataSource(DruidDataSourceCreator.java:158)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDruidDataSource(DataSourceCreator.java:174)
	at com.baomidou.dynamic.datasource.creator.DataSourceCreator.createDataSource(DataSourceCreator.java:92)
	at com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider.createDataSourceMap(AbstractDataSourceProvider.java:45)
	at com.baomidou.dynamic.datasource.provider.YmlDynamicDataSourceProvider.loadDataSources(YmlDynamicDataSourceProvider.java:43)
	at com.baomidou.dynamic.datasource.DynamicRoutingDataSource.afterPropertiesSet(DynamicRoutingDataSource.java:229)
	at 

**To Reproduce**
master链接mysql正常init，taos无法init

**Expected Behavior**
使用@DS切换数据源
