### ISSUE TITLE
What is the correct way to use the env TAOS_SECOND_EP?

### ISSUE THREAD

**Issue by bioinformatist** [taosdata/TDengine#16598]
I've using TDengine in production for several months. Since an HA cluster is necessary, recently I built a new cluster with `docker swarm`.

According to the document, HA cluster need the `TAOS_SECOND_EP` value, and if the first EP is not reachable, the dnode will try connect to this specified second EP. So I made my `docker-composer.yml` like this:

```yaml
version: "3.9"

networks:
  inter:

services:
  td-1:
    image: localhost:5000/tdengine/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td1:/var/lib/taos/
      - taoslog-td1:/var/log/taos/
  td-2:
    image: localhost:5000/tdengine/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-3"
    volumes:
      - taosdata-td2:/var/lib/taos/
      - taoslog-td2:/var/log/taos/
  td-3:
    image: localhost:5000/tdengine/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td3:/var/lib/taos/
      - taoslog-td3:/var/log/taos/

volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
  taosdata-td3:
  taoslog-td3:
```

Then I called `docker stack deploy -c docker-compose.yml kun` to deploy on a swarm cluster with three physical server, with one as manager as well as two workers.

The `docker stack ps kun` output was:

```pre
ID             NAME         IMAGE                                     NODE        DESIRED STATE   CURRENT STATE                    ERROR     PORTS
z837klqu5t1v   kun_td-1.1   localhost:5000/tdengine/tdengine:latest   server-01   Running         Running less than a second ago
i7lg9gs995r9   kun_td-2.1   localhost:5000/tdengine/tdengine:latest   server-01   Running         Running less than a second ago
13p9dghfkaz2   kun_td-3.1   localhost:5000/tdengine/tdengine:latest   server-02   Running         Running less than a second ago
```

The story came to `server-02`, I called `docker ps` to get the contaner id as `5ce1addd6dbe`, and then got its prompt by `docker exec -it 5ce1addd6dbe bash`.

To check the cluster healthy:

```bash
taos -s "show dnodes"
```

And the output was:

```pre
taos> show dnodes;
     id      |            endpoint            | vnodes | support_vnodes |   status   |       create_time       |              note              |
=================================================================================================================================================
           1 | td-1:6030                      |      2 |            128 | ready      | 2022-09-01 11:52:57.426 |                                |
           2 | td-2:6030                      |      1 |              0 | offline    | 2022-09-01 11:52:58.013 | clusterId not match            |
           3 | td-3:6030                      |      3 |            128 | ready      | 2022-09-01 11:52:58.090 |                                |
```

I also checked the logs of container:

```pre
...
09/01 14:34:28.524880 00000073 MND trans:6, is proposed and post sem
09/01 14:34:28.607805 00000071 MND dnode:1, mnode syncstate from error to leader
09/01 14:34:28.607841 00000071 MND dnode:1, td-1:6030 first access, clusterId:7024848321488223014
09/01 14:34:28.607858 00000071 MND dnode:1, from offline to online, memory avail:14844148122 total:16512139264 cores:8.00
09/01 14:34:28.608187 00000082 DND set local info, dnodeId:1 clusterId:7024848321488223014
09/01 14:34:28.627443 00000072 MND dnode:td-2:6030, start to create
09/01 14:34:28.627825 00000073 MND trans:7, is proposed and post sem
09/01 14:34:28.628210 00000073 MND trans:7, is proposed and post sem
09/01 14:34:40.639237 00000071 UTL ERROR http-report failed to get http server:telemetry.taosdata.com ip since Resource temporarily unavailable
09/01 14:34:40.639278 00000071 MND ERROR failed to send telemetry msg
09/01 14:34:40.639312 00000071 MND dnode:1, from offline to online, memory avail:14844148122 total:16512139264 cores:8.00
09/01 14:34:40.639450 00000071 MND ERROR dnode:3, clusterId 7197928727239210812 not match exist 7024848321488223014
09/01 14:34:40.639464 00000071 MND ERROR msg:0x7fdb98001310, failed to process since Cluster id not match, app:0x9527 type:status, gtid:0x0:0x58c0917a44ee0001
09/01 14:34:40.639488 00000071 MND ERROR dnode:2, clusterId 7187422579557433145 not match exist 7024848321488223014
09/01 14:34:40.639494 00000071 MND ERROR msg:0x7fdbb4004350, failed to process since Cluster id not match, app:0x9527 type:status, gtid:0x0:0x50a0957ad62d0002
09/01 14:34:40.840847 00000071 MND ERROR dnode:3, clusterId 7197928727239210812 not match exist 7024848321488223014
09/01 14:34:40.840902 00000071 MND ERROR msg:0x7fdb98001580, failed to process since Cluster id not match, app:0x9527 type:status, gtid:0x0:0x58c0917a6a740002
09/01 14:34:40.840931 00000071 MND ERROR dnode:2, clusterId 7187422579557433145 not match exist 7024848321488223014
09/01 14:34:40.840938 00000071 MND ERROR msg:0x7fdbb4004960, failed to process since Cluster id not match, app:0x9527 type:status, gtid:0x0:0x50a0957afb430003
09/01 14:34:41.842409 00000071 MND ERROR dnode:2, clusterId 7187422579557433145 not match exist 7024848321488223014
09/01 14:34:41.842471 00000071 MND ERROR msg:0x7fdbb4004d40, failed to process since Cluster id not match, app:0x9527 type:status, gtid:0x0:0x50a0957aff2c0004
09/01 14:34:41.842498 00000071 MND ERROR dnode:3, clusterId 7197928727239210812 not match exist 7024848321488223014
09/01 14:34:41.842504 00000071 MND ERROR msg:0x7fdb980017f0, failed to process since Cluster id not match, app:0x9527 type:status, gtid:0x0:0x58c0917a6e5d0003
```

So what's wrong here?

**Comment by zitsen** [comment]
```yaml
td-2:
    image: localhost:5000/tdengine/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-3"
```

Here TAOS_SECOND_EP should not be used for node td-2.

**Comment by bioinformatist** [comment]
@zitsen The problem appears to be caused by other services. With only a TDengine cluster deployed, no error occurs even the node `td-2` holds the previous `TAOS_SECOND_EP` value. I'm still looking for the real failure point.

**Comment by bioinformatist** [comment]
Well, it is caused by [Caddy 2](https://caddyserver.com/v2). Caddy cannot be used as reverse proxy among docker containers by label. To solve it, I finally use [Caddy-Docker-Proxy](https://github.com/lucaslorentz/caddy-docker-proxy). And it DO works. 

Below is my `docker-compose.yml`:

```yaml
version: "3.9"

networks:
  inter:

services:
  td-1:
    build:
      dockerfile: ./docker/tdengine.Dockerfile
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment: 
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td1:/var/lib/taos/
      - taoslog-td1:/var/log/taos/
  td-2:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-3"
    volumes:
      - taosdata-td2:/var/lib/taos/
      - taoslog-td2:/var/log/taos/
  td-3:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td3:/var/lib/taos/
      - taoslog-td3:/var/log/taos/

  adapter:
    image: localhost:5000/kun/tdengine
    entrypoint: "taosadapter"
    networks:
      - inter
    labels:
      caddy_0: localhost:6041
      caddy_0.reverse_proxy: adapter:6041
      caddy_1: localhost:6044
      caddy_1.reverse_proxy: adapter:6044
    environment:
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2

  caddy-docker-proxy:
    build: 
      dockerfile: ./docker/caddy-docker-proxy.Dockerfile
    image: localhost:5000/kun/caddy-docker-proxy
    networks:
      - inter
    ports:
      - 6041:6041
      - 6044:6044/udp
    environment:
      - CADDY_INGRESS_NETWORKS=inter
    volumes:
      - caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2
    
  caddy:
    build: 
      dockerfile: ./docker/caddy.Dockerfile
    image: localhost:5000/kun/caddy
    networks:
      - inter
    ports:
      - 80:80
    volumes:
      - caddy_data:/data
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2

  kun:
    build: 
      dockerfile: ./docker/kun.Dockerfile
      args:
        - TAOSD_VER=3.0.1.0
        - TAOSTOOLS_VER=2.1.3
    image: localhost:5000/kun/kun
    networks:
      - inter
    volumes:
      - sshfsdata:/local
      - /home/ysun/work:/work
    command: php Kun.php --server_name=adapter --user=root --password=taosdata --local_dir=/local --work_dir=/work --min_start_count=3000 --min_update_count=1000 --mes_addr=server-02:8000 --config=presets/dfd.json --proc_num=20 start
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2

volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
  taosdata-td3:
  taoslog-td3:
  caddy_data:
  sshfsdata:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "ysun@manager:/home/ysun/local"
      password: 930829
```

**Comment by bioinformatist** [comment]
Well, it is caused by [Caddy 2](https://caddyserver.com/v2). Caddy cannot be used as reverse proxy among docker containers by label. To solve it, I finally use [Caddy-Docker-Proxy](https://github.com/lucaslorentz/caddy-docker-proxy). And it DO works. 

Below is my `docker-compose.yml`:

```yaml
version: "3.9"

networks:
  inter:

services:
  td-1:
    build:
      dockerfile: ./docker/tdengine.Dockerfile
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment: 
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td1:/var/lib/taos/
      - taoslog-td1:/var/log/taos/
  td-2:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-3"
    volumes:
      - taosdata-td2:/var/lib/taos/
      - taoslog-td2:/var/log/taos/
  td-3:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td3:/var/lib/taos/
      - taoslog-td3:/var/log/taos/

  adapter:
    image: localhost:5000/kun/tdengine
    entrypoint: "taosadapter"
    networks:
      - inter
    labels:
      caddy_0: localhost:6041
      caddy_0.reverse_proxy: adapter:6041
      caddy_1: localhost:6044
      caddy_1.reverse_proxy: adapter:6044
    environment:
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2

  caddy-docker-proxy:
    build: 
      dockerfile: ./docker/caddy-docker-proxy.Dockerfile
    image: localhost:5000/kun/caddy-docker-proxy
    networks:
      - inter
    ports:
      - 6041:6041
      - 6044:6044/udp
    environment:
      - CADDY_INGRESS_NETWORKS=inter
    volumes:
      - caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2
    
  caddy:
    build: 
      dockerfile: ./docker/caddy.Dockerfile
    image: localhost:5000/kun/caddy
    networks:
      - inter
    ports:
      - 80:80
    volumes:
      - caddy_data:/data
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2

  kun:
    build: 
      dockerfile: ./docker/kun.Dockerfile
      args:
        - TAOSD_VER=3.0.1.0
        - TAOSTOOLS_VER=2.1.3
    image: localhost:5000/kun/kun
    networks:
      - inter
    volumes:
      - sshfsdata:/local
      - /home/ysun/work:/work
    command: php Kun.php ...
    deploy:
      placement:
        constraints:
          - "node.role==worker"
        max_replicas_per_node: 1
      replicas: 2

volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
  taosdata-td3:
  taoslog-td3:
  caddy_data:
  sshfsdata:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "ysun@manager:/home/ysun/local"
      password: ******
```
