### ISSUE TITLE
path: taosd/udfd, error: no such file or directory

### ISSUE THREAD

**Issue by zhfish** [taosdata/TDengine#16733]
**Bug Description**
`UDF ERROR can not spawn udfd. path: taosd/udfd, error: no such file or directory`
**To Reproduce**
```
version: '2'

services:
  taos:
    container_name: TDengine
    ports:
      - "6030:6030"
      - "6041:6041"
      - "6043-6049:6043-6049"
      - "6043-6049:6043-6049/udp"
    image: tdengine/tdengine:3.0.1.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/taos/lib:/var/lib/taos/
      - /data/taos/log:/var/log/taos/
    restart: unless-stopped
```

**Environment (please complete the following information):**
 - OS: Centos7, Kernal: 5.19.4
 - Memory, CPU, current Disk Space
 - TDengine Version 3.0.1.0

**Additional Context**
全新目录
用我的docker-compose即可复现

#16449 
#16192
