### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by zeje** [taosdata/TDengine#18276]
环境：
cpu 12核，20核心线程，64G内存，双固态硬盘（tdeinge存储于在挂载的第二块固态硬盘）
（一台电脑部署应用程序，缓存，关系数据库，tdengine）

从3.0.1.6升级至3.0.1.7（数据从0重新插入，查询策略细微调整），出现一个现象：
1. 3.0.1.6 taosd 内存8G左右。应用程序内存17G多。总体看上去能平稳。
![2347476fb5d87f1bac216b4499cb1c4](https://user-images.githubusercontent.com/10680634/202836273-8c544aac-ab6f-4802-88ae-7422edb232a6.png)

2. 3.0.1.7 taosd 内存12G多。应用程序内存19G多，总体看上去是上升，且还在上升。
![8 HGJGR(V8NZUW1@ 567VQ](https://user-images.githubusercontent.com/10680634/202836265-c83a0652-f482-4c00-b8fc-ecc40836955f.png)

建库语句
`
create DATABASE `db` 
BUFFER 1024  
COMP 2 
DURATION 1d 
WAL_FSYNC_PERIOD 3000 
MAXROWS 8192 
MINROWS 100 
KEEP 366d,366d,366d 
PAGES 512 
PAGESIZE 16 
precision 'ms' 
REPLICA 1 
STRICT 'off' 
WAL_LEVEL 1 
VGROUPS 20 
SINGLE_STABLE 0
`

超级表
`
CREATE STABLE `event_tdstore_status` (`_ts` TIMESTAMP, `dateTime` BIGINT, `isHomeWifi` BOOL, `isChargingComplete` BOOL, `isHistoricalData` BOOL, `fallDownStatus` INT, `workMode` INT, `dataType` VARCHAR(32), `isBeacon` BOOL, `isCharging` BOOL, `isHome` BOOL, `bleConnected` BOOL, `battery` INT, `isBLE` BOOL, `isSmart` BOOL, `isAGPS` BOOL, `createTime` BIGINT, `isWIFI` BOOL, `isGPS` BOOL, `signalSize` INT, `isReboot` BOOL, `statusCode` BIGINT, `isGMS` BOOL, `isMotion` BOOL) TAGS (`productId` VARCHAR(64), `deviceId` VARCHAR(64))
`

`
CREATE STABLE `event_tdstore_isactitem` (`_ts` TIMESTAMP, `datetime` BIGINT, `createTime` BIGINT, `active` INT) TAGS (`productId` VARCHAR(64), `deviceId` VARCHAR(64))
`

`
CREATE STABLE `event_tdstore_gps` (`_ts` TIMESTAMP, `satellites` FLOAT, `altitude` FLOAT, `lng` DOUBLE, `createTime` BIGINT, `precision` FLOAT, `lat` DOUBLE, `speed` FLOAT, `direction` FLOAT, `mileage` FLOAT) TAGS (`productId` VARCHAR(64), `deviceId` VARCHAR(64))
`
插入：jdbc
数据时间

`createTime`时间：2022-11-17 18:27:08.360 至 2022-11-19 13:50:44.935
_ts时间：2022-01-01 04:12:30至2022-01-19 06:45:06

select count(_ts) from db.event_tdstore_isActItem; --103135079 
select count(_ts) from db.event_tdstore_generallocation; --49508824
select count(_ts) from db.event_tdstore_gps; -- 49522963
select count(_ts) from db.event_tdstore_status; -- 49522965

查询：rest
2022-11-18 12:27:08.360 至 2022-11-19 13:50:44.935 
查询一：
1. 查询策略：
2. 查询最新数据的_ts时间:  select _ts from db.event_tdstore_gps_子表  order by _ts desc limit 1 offset 0
3. 查询最新七天的数据top50: select * from db.event_tdstore_gps_子表 where _ts > 七天前的时间 order by _ts desc limit 50 offset 0

查询二：
1. 查询策略
select * from db.event_tdstore_isactitem子表 order by _ts desc limit 2000 offset 0

![PI1W~R(2@QS) K38QB8XL1A](https://user-images.githubusercontent.com/10680634/202837655-d8ec4514-6c9f-4687-9549-2964baff4331.png)

**Comment by zeje** [comment]
停掉http压力测试后，内存不再上涨。

**Comment by zeje** [comment]
不是3.0.1.7的问题，3.0.1.6也会，但是3.0.1.7的涨幅较大。
如下是3.0.1.6的
![{}POAD3YAPHAO(%{40303FN](https://user-images.githubusercontent.com/10680634/203233698-1230d018-4cb1-4e4b-8b25-48eb1b743852.png)

**Comment by mojerro** [comment]
我也遇到了这个问题，内存持续上涨，而且夜间有一天突然打满。目前只是吧tdengine当做prometheus的外部读写，平时用量较小，日志量只有2个服务器的，也不大。
![image](https://user-images.githubusercontent.com/15071824/203476557-43a6aef3-4c54-4a7f-94c1-594e8ed9f220.png)
![image](https://user-images.githubusercontent.com/15071824/203476702-81dc6000-c765-4498-a8ad-b7916cee149b.png)

docker部署的3.0.1.2版本

**Comment by mojerro** [comment]
@yu285 辛苦大佬帮忙看一下呗~

**Comment by yu285** [comment]
> 从数据来说，肯定是线性增长的，而查询一般
> 
> 1. 查最新的n条
> 2. 距今多少时间的数据。
>    随着时间的迁移，原来需要查的数据，已经不需要查了，但是这一部分的数据（可能是某种缓存）一直被驻留在内存中。只要有一个超时机制，释放，问题就解决了。

麻烦提供一下复现代码吧，我们跑一下

**Comment by zeje** [comment]
通过远程协助，发现日志级别，对性能影响太大了。

show dnodes;
alter dnode 1 'tsdbdebugflag' '131';
alter dnode 1 'qdebugflag' '131';  

需要重新压测，再反馈是否有问题

@yu285 感谢大佬鼎力相助

**Comment by zeje** [comment]
3.0.1.7升级到3.0.1.8（非docker），一启动查询压力测试，直接崩，暂时只能下面的信息。
java: /home/ubuntu/workroom/jenkins/3.0/TDinternal/community/source/libs/catalog/src/ctgRemote.c:31：ctgHandleBatchRsp: 假设 ‘taskNum == msgNum || 0 == msgNum’ 失败。
^C
因为环境切来切去，没有生成core，然后重新启动后重新压力测试，没复现上面的异常了。

当前（2022-11-28 11:25）目前单表2.4w*2w大概4-5亿条记录，四张超级表，总数据量10亿+

**Comment by yu285** [comment]
内存还涨么

**Comment by zeje** [comment]
> 内存还涨么

3.0.1.7测试到内存达到一定程度后，执行超级表count查询没响应，crash之后，升级到3.0.1.8。
目前只压力测试一天，表现如下：

38-40这个是我应用程序的问题，tdengine 3.0.1.8目前看，在趋向稳定，但还是微量上涨

![X}V H}1NQNHA6SR%~0LB_AN](https://user-images.githubusercontent.com/10680634/204413450-d5a2fdf4-114e-40e0-a738-35a07ae18dfe.png)

**Comment by mojerro** [comment]
我这边是挂着就会涨，重新弄还是一样，，，官方可以试一下，找个服务器，用docker compose吧tdengine作为prometheus后端，监控采集本机运行两天就能复现

**Comment by yu285** [comment]
> 我这边是挂着就会涨，重新弄还是一样，，，官方可以试一下，找个服务器，用docker compose吧tdengine作为prometheus后端，监控采集本机运行两天就能复现

请问是无限制增长直到 OOM 么

**Comment by mojerro** [comment]
> > 我这边是挂着就会涨，重新弄还是一样，，，官方可以试一下，找个服务器，用docker compose吧tdengine作为prometheus后端，监控采集本机运行两天就能复现
> 
> 请问是无限制增长直到 OOM 么

是的，抱歉邮件没看到，回复晚了

**Comment by zeje** [comment]
> > > 我这边是挂着就会涨，重新弄还是一样，，，官方可以试一下，找个服务器，用docker compose吧tdengine作为prometheus后端，监控采集本机运行两天就能复现
> > 
> > 
> > 请问是无限制增长直到 OOM 么
> 
> 是的，抱歉邮件没看到，回复晚了

请把你的电脑配置，版本，还有环境搭建脚本，发一下吧。

我这边今天是第五天了，还没OOM，不过内存还是继续涨

**Comment by mojerro** [comment]
> > > > 我这边是挂着就会涨，重新弄还是一样，，，官方可以试一下，找个服务器，用docker compose吧tdengine作为prometheus后端，监控采集本机运行两天就能复现
> > > 
> > > 
> > > 请问是无限制增长直到 OOM 么
> > 
> > 
> > 是的，抱歉邮件没看到，回复晚了
> 
> 请把你的电脑配置，版本，还有环境搭建脚本，发一下吧。
> 
> 我这边今天是第五天了，还没OOM，不过内存还是继续涨

OOM几乎是必然的，我内存比较少，可能饱的快。但是一直涨早晚OOM，我觉得这个跟配置没关系

服务器是8c16g，还部署了好多其他项目

docker-compose配置可以参考一下，用的夜莺的部署demo改的

```yaml
version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./nightingale/prometc:/etc/prometheus:ro
      - prometheus-data:/prometheus
    ports:
      - "39090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--enable-feature=remote-write-receiver"
      - "--query.lookback-delta=2m"
    networks:
      - nightingale

  grafana:
    image: grafana/grafana:9.0.9
    container_name: grafana
    restart: unless-stopped
    ports:
      - 33000:3000
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nightingale/grafana/provisioning:/etc/grafana/provisioning
      - ./nightingale/grafana/dashboards:/var/lib/grafana/dashboards
      - ./nightingale/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana
    networks:
      - nightingale

  nwebapi:
    image: flashcatcloud/nightingale:latest
    container_name: nwebapi
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: release
      WAIT_HOSTS: postgres:5432, redis:6379
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nightingale/n9eetc:/app/etc:ro
    ports:
      - "18000:18000"
    command: >
      sh -c "/wait && /app/n9e webapi"
    networks:
      - nightingale

  nserver:
    image: flashcatcloud/nightingale:latest
    container_name: nserver
    restart: unless-stopped
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: postgres:5432, redis:6379
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nightingale/n9eetc:/app/etc:ro
    ports:
      - "19000:19000"
    command: >
      sh -c "/wait && /app/n9e server"
    networks:
      - nightingale

  redis:
    image: ${REDIS_IMAGE}
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - redis-data:/data
    # ports:
    #   - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - nightingale
  tdengine:
    image: tdengine/tdengine:3.0.1.2
    restart: unless-stopped
    environment:
      TAOS_FQDN: "tdengine"
    ports:
      - 36030:6030
      - 36041:6041
      - 36043:6043
    volumes:
      - tdengine-data:/var/lib/taos/
      - tdengine-log:/var/log/taos/
    networks:
      db-net:


volumes:
  tdengine-data:
    driver: local
  tdengine-log:
    driver: local
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

```
