### ISSUE TITLE
mybatisplus-demo建表报错: this operation is NOT supported currently

### ISSUE THREAD

**Issue by charmingPing** [taosdata/TDengine#18703]
**Description**
mybatisplus-demo 分支2.6
项目可以正常启动，但建表报错：this operation is NOT supported currently!
如何解决这个问题？
```
spring:
  datasource:
    url: jdbc:TAOS-RS://192.168.4.26:6041/test?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    username: root
    password: taosdata
```

**Screenshots**
![image](https://user-images.githubusercontent.com/45278072/205562781-8d5aa17c-2e3f-44fa-a01a-483e2c966545.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - TDengine Version 2.6.0.4
 - Docker 20.10.9
