### ISSUE TITLE
TDengine couldn't restart service

### ISSUE THREAD

**Issue by sytuacmdyh** [taosdata/TDengine#18939]
**Bug Description**
正式环境运行出错后，无法重新启动
docker-compose.yml及错误日志见附件

**To Reproduce**
1. docker-compose up -d

**Expected Behavior**
启动成功

**Environment (please complete the following information):**
 - docker [19.03.2]
 - TDengine Version [3.0.1.8]

```
version: "3.7"

x-log: &default-logging
  driver: json-file
  options:
    max-size: "256k"
    max-file: "4"

services:
  tdenginetest:
    image: tdengine/tdengine:3.0.1.8
    logging: *default-logging
    volumes:
      - ./test/data:/var/lib/taos/
      - ./test/log:/var/log/taos/
      - ./test/etc/taos.cfg:/etc/taos/taos.cfg
```

[tdengine.log](https://github.com/taosdata/TDengine/files/10224165/tdengine.log)
