### ISSUE TITLE
3.0.2.2 create mnode execution stuck

### ISSUE THREAD

**Issue by lazyky** [taosdata/TDengine#19340]
**Bug Description**
使用docker-compose部署 TDengine Swarm集群，’ CREATE MNODE ON DNODE dnode_id‘ 执行后无反应，命令没有报错和正确执行

**To Reproduce**
1. 使用docker-compose构建Docker Swarm TDengine 集群
2. ’show mnodes' 以及  ’show dnodes' 均正常
3. ’ CREATE MNODE ON DNODE dnode_id‘ 执行后无反应，logs不见异常

**Expected Behavior**
能够正常创建mnode，以实现集群高可用

**Screenshots**
![image](https://user-images.githubusercontent.com/24838473/210339049-e6e9cccc-d41d-47be-9b85-a3414ef41591.png)

**Environment (please complete the following information):**
 - OS: docker image tdengine/tdengine:3.0.2.2
 - 8G Memory, i5-1135G7, 512G SSD
 - TDengine Version: 3.0.2.2

**Additional Context**
附件为tdengine container的日志
[tdengine_3.0.2.2.zip](https://github.com/taosdata/TDengine/files/10335827/tdengine_3.0.2.2.zip)

**Docker Compose File**
```
version: "3.9"

services:
  td-1:
    build:
      dockerfile: ./docker/tdengine.Dockerfile
      args:
        TAOSD_VER: 3.0.2.2
        TZ: Asia/Shanghai
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment: 
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td1:/var/lib/taos/
      - taoslog-td1:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==manager
  td-2:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-3"
    volumes:
      - taosdata-td2:/var/lib/taos/
      - taoslog-td2:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==server-01
  td-3:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td3:/var/lib/taos/
      - taoslog-td3:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==server-02

  adapter:
    image: localhost:5000/kun/tdengine
    entrypoint: "taosadapter"
    networks:
      - inter
    environment:
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    deploy:
      labels:
        caddy_0: localhost:6041
        caddy_0.reverse_proxy: adapter:6041
        caddy_1: localhost:6044
        caddy_1.reverse_proxy: adapter:6044
      mode: global
      placement:
        constraints: 
          - node.role == manager

  caddy-docker-proxy:
    build: 
      dockerfile: ./docker/caddy-docker-proxy.Dockerfile
    image: localhost:5000/kun/caddy-docker-proxy
    networks:
      - inter
    ports:
      - 6041:6041
      - 6044:6044/udp
      - 80:80
      - 5188:5188
    environment:
      - CADDY_INGRESS_NETWORKS=inter
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/Caddyfile
    volumes:
      - caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager

networks:
  inter:
  host:
    external: true
volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
  taosdata-td3:
  taoslog-td3:
  caddy_data:
```

**Comment by yu285** [comment]
可能需要远程一下，可以加微信 a15652223354

**Comment by lazyky** [comment]
### docker-compose 部署
```
version: "3.9"

services:
  td-1:
    build:
      dockerfile: ./docker/tdengine.Dockerfile
      args:
        TAOSD_VER: 3.0.2.2
        TZ: Asia/Shanghai
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment: 
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td1:/var/lib/taos/
      - taoslog-td1:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==manager
  td-2:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-3"
    volumes:
      - taosdata-td2:/var/lib/taos/
      - taoslog-td2:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==server-01
  td-3:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td3:/var/lib/taos/
      - taoslog-td3:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==server-02

  adapter:
    image: localhost:5000/kun/tdengine
    entrypoint: "taosadapter"
    networks:
      - inter
    environment:
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    deploy:
      labels:
        caddy_0: localhost:6041
        caddy_0.reverse_proxy: adapter:6041
        caddy_1: localhost:6044
        caddy_1.reverse_proxy: adapter:6044
      mode: global
      placement:
        constraints: 
          - node.role == manager

  caddy-docker-proxy:
    build: 
      dockerfile: ./docker/caddy-docker-proxy.Dockerfile
    image: localhost:5000/kun/caddy-docker-proxy
    networks:
      - inter
    ports:
      - 6041:6041
      - 6044:6044/udp
      - 80:80
      - 5188:5188
    environment:
      - CADDY_INGRESS_NETWORKS=inter
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/Caddyfile
    volumes:
      - caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager

networks:
  inter:
  host:
    external: true
volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
  taosdata-td3:
  taoslog-td3:
  caddy_data:
```
