### ISSUE TITLE
tdengine-3.0.2.4 swarm cluster (3mnode-3dnodes-3replica):  2/3 nodes restart cannot be recovered

### ISSUE THREAD

**Issue by lazyky** [taosdata/TDengine#19837]
**Bug Description**

三个低性能 PC 的 docker swarm 集群灾备测试 ( 3mnode-3dnodes-3replica )
-   单独关闭 `server-01/server-02`, 插入数据，`TDengine` 集群运行正常, 可看到同步日志
-   同时关闭 `server-01` 和 `server-02`, 重新开机后，`td-2` 和 `td-3` 显示以下报错，`TDengine` 集群无法正常部署
```
kun_td-2.1.ktrldl0v6p8k@server-01    | 2: service ok
kun_td-2.1.ktrldl0v6p8k@server-01    | execute create dnode
kun_td-2.1.ktrldl0v6p8k@server-01    | Welcome to the TDengine Command Line Interface, Client Version:3.0.2.4
kun_td-2.1.ktrldl0v6p8k@server-01    | Copyright (c) 2022 by TDengine, all rights reserved.
kun_td-2.1.ktrldl0v6p8k@server-01    | 
kun_td-2.1.ktrldl0v6p8k@server-01    | failed to connect to server, reason: Sync not leader
kun_td-2.1.ktrldl0v6p8k@server-01    | 
```

**To Reproduce**
- 构建swarm集群，重启两个节点（或重启集群）

**Expected Behavior**
重启后，正常部署 tdengine 集群

**Screenshots**

**Environment (please complete the following information):**
 - OS: ubuntu 22.04 LTS
 - 8G Memory, CPU i5-1135G7, 512G SSD
 - TDengine Version 3.0.2.4

**Additional Context**

**Comment by LZK-1994** [comment]
我这也遇到了这样的问题，目前还没解决，头疼。

**Comment by yu285** [comment]
mnode 是几副本

**Comment by yu285** [comment]
可以升级到 3.0.3.0 问题还在的话，我可以远程看下

**Comment by yu285** [comment]
这个应该是docker自己的域名解析机制导致的。

**Comment by lazyky** [comment]
#### 更新至3.0.3.0，重启集群仍会报错
- 重启两个节点可以正常部署集群
- 重启整个集群(三个节点)，部署时出现以下报错 `failed to connect to server, reason: Sync not leader`

```
kun_td-2.1.70jkcsew4dfy@server-01    | sysctl: setting key "kernel.core_pattern": Read-only file system
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.681045 00000034 TAOS_ADAPTER info "start server:00000034" model=main
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
kun_td-2.1.70jkcsew4dfy@server-01    |  - using env:    export GIN_MODE=release
kun_td-2.1.70jkcsew4dfy@server-01    |  - using code:   gin.SetMode(gin.ReleaseMode)
kun_td-2.1.70jkcsew4dfy@server-01    | 
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/             --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/cmdline      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/profile      --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/symbol       --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/trace        --> github.com/gin-gonic/gin.WrapF.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/allocs       --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/block        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/goroutine    --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/heap         --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/mutex        --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /debug/pprof/threadcreate --> github.com/gin-gonic/gin.WrapH.func1 (3 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /metrics                  --> github.com/gin-gonic/gin.WrapH.func1 (5 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /-/ping                   --> github.com/taosdata/taosadapter/v3/controller/ping.Controller.Init.func1 (5 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /rest/sql                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /rest/sql/:db             --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).sql-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /rest/sql/:db/vgid        --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tableVgID-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /rest/login/:user/:password --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).des-fm (6 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /rest/ws                  --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).ws-fm (6 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /rest/stmt                --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).stmt-fm (6 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /rest/tmq                 --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).tmq-fm (6 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /rest/upload              --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).upload-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /rest/schemaless          --> github.com/taosdata/taosadapter/v3/controller/rest.(*Restful).schemalessWs-fm (6 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] GET    /genauth/:user/:password/:key --> github.com/taosdata/taosadapter/v3/plugin.RegisterGenerateAuth.func1 (5 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.681505 00000034 TAOS_ADAPTER info "init plugin opentsdb_telnet/v1" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.682792 00000034 TAOS_ADAPTER info "opentsdb_telnet disabled" model=opentsdb_telnet
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.682834 00000034 TAOS_ADAPTER info "init plugin prometheus/v1" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /prometheus/v1/remote_read/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Read-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /prometheus/v1/remote_write/:db --> github.com/taosdata/taosadapter/v3/plugin/prometheus.(*Plugin).Write-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.683082 00000034 TAOS_ADAPTER info "init plugin statsd/v1" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.685213 00000034 TAOS_ADAPTER info "statsd disabled" model=statsd
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.685262 00000034 TAOS_ADAPTER info "init plugin collectd/v1" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.686399 00000034 TAOS_ADAPTER info "collectd disabled" model=collectd
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.686416 00000034 TAOS_ADAPTER info "init plugin influxdb/v1" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /influxdb/v1/write        --> github.com/taosdata/taosadapter/v3/plugin/influxdb.(*Influxdb).write-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.686597 00000034 TAOS_ADAPTER info "init plugin node_exporter/v1" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.688901 00000034 TAOS_ADAPTER info "node_exporter disabled" model=NodeExporter
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.688911 00000034 TAOS_ADAPTER info "init plugin opentsdb/v1" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /opentsdb/v1/put/json/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertJson-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | [GIN-debug] POST   /opentsdb/v1/put/telnet/:db --> github.com/taosdata/taosadapter/v3/plugin/opentsdb.(*Plugin).insertTelnet-fm (7 handlers)
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.689332 00000034 TAOS_ADAPTER info "all plugin init finish" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.689379 00000034 TAOS_ADAPTER info "all plugin start finish" model=plugin
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.689502 00000034 TAOS_ADAPTER info "Running in terminal." model=main
kun_td-2.1.70jkcsew4dfy@server-01    | 03/20 11:23:55.690752 00000034 TAOS_ADAPTER info "server on : 6041" model=main
kun_td-2.1.70jkcsew4dfy@server-01    | 2: service ok
kun_td-2.1.70jkcsew4dfy@server-01    | execute create dnode
kun_td-2.1.70jkcsew4dfy@server-01    | Welcome to the TDengine Command Line Interface, Client Version:3.0.3.0
kun_td-2.1.70jkcsew4dfy@server-01    | Copyright (c) 2022 by TDengine, all rights reserved.
kun_td-2.1.70jkcsew4dfy@server-01    | 
kun_td-2.1.70jkcsew4dfy@server-01    | failed to connect to server, reason: Sync not leader
kun_td-2.1.70jkcsew4dfy@server-01    | 
```

- docker-compose.yml
```
version: "3.9"

services:
  td-1:
    build:
      dockerfile: ./docker/tdengine.Dockerfile
      args:
        TAOSD_VER: 3.0.3.0
        TZ: Asia/Shanghai
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment: 
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    volumes:
      - taosdata-td1:/var/lib/taos/
      - taoslog-td1:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==manager
  td-2:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-3"
    volumes:
      - taosdata-td2:/var/lib/taos/
      - taoslog-td2:/var/log/taos/
    deploy: 
      placement:
        constraints:
          - node.hostname==server-01
  td-3:
    image: localhost:5000/kun/tdengine
    networks:
      - inter
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
      
    volumes:
      - taosdata-td3:/var/lib/taos/
      - taoslog-td3:/var/log/taos/
    deploy:
      placement:
        constraints:
          - node.hostname==server-02

  adapter:
    image: localhost:5000/kun/tdengine
    # 使用 taos -s 检测 dnodes 状态, 都为 2 时 create mnodes
    entrypoint: ["/bin/bash", "-c", "while true; \
     do \
     status=$$(taos -h td-1 -t | awk -F: '{printf $$1}' && taos -h td-2 -t | awk -F: '{printf $$1}' && taos -h td-3 -t | awk -F: '{printf $$1}'); \
     status_count=$$(awk -F2 '{print NF-1}' <<< $$status); \
     if [ $$status_count -eq 3 ]; then taos -s 'create mnode on dnode 2;create mnode on dnode 3'; break; fi; \
     done && \
     taosadapter"]
    networks:
      - inter
    environment:
      TAOS_FIRST_EP: "td-1"
      TAOS_SECOND_EP: "td-2"
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager

networks:
  inter:

volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
  taosdata-td3:
  taoslog-td3:
```
