### ISSUE TITLE
tarbitrator not found

### ISSUE THREAD

**Issue by DRRRRRRRRRRRRR** [taosdata/TDengine#19922]
**Bug Description**
Tarbitrator not found when i use offical docker-compose.yml up

**To Reproduce**
1.  just download offical docker-compose.yml
2.  set version
3.  docker-compose up -d
4.  will see the error `tarbitrator not found` when i use the command `docker-compose logs -f | grep tdengine-arbitrator-1`

**Environment (please complete the following information):**
 - OS: CentOS 7.0
 - TDengine Version 3.0.2.4

**Comment by DRRRRRRRRRRRRR** [comment]
here is the docker-compose.yml
``` yml
version: "3"
services:
  arbitrator:
    image: tdengine/tdengine:$VERSION
    command: tarbitrator
  td-1:
    image: tdengine/tdengine:$VERSION
    environment:
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
      TAOS_NUM_OF_MNODES: "2"
      TAOS_REPLICA: "2"
      TAOS_ARBITRATOR: arbitrator:6042
    volumes:
      - taosdata-td1:/var/lib/taos/
      - taoslog-td1:/var/log/taos/
  td-2:
    image: tdengine/tdengine:$VERSION
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
      TAOS_NUM_OF_MNODES: "2"
      TAOS_REPLICA: "2"
      TAOS_ARBITRATOR: arbitrator:6042
    volumes:
      - taosdata-td2:/var/lib/taos/
      - taoslog-td2:/var/log/taos/
volumes:
  taosdata-td1:
  taoslog-td1:
  taosdata-td2:
  taoslog-td2:
```
