### ISSUE TITLE
udfd一直重启

### ISSUE THREAD

**Issue by BestNathan** [taosdata/TDengine#21133]
使用Docker启动 3.0.4.0 镜像，节点是起来了，但是日志一直报

日志：
```
05/02 14:38:01.500058 00000085 UDF udfd LD_LIBRARY_PATH: :/usr/lib
05/02 14:38:01.500907 00000085 UDF udfd is initialized
05/02 14:38:01.503990 00000085 UDF udfd process exited with status 251, signal 0
05/02 14:38:01.503994 00000085 UDF udfd process restart
05/02 14:38:01.503995 00000085 UDF start to init udfd
05/02 14:38:01.503997 00000085 UDF udfd LD_LIBRARY_PATH: :/usr/lib
05/02 14:38:01.504913 00000085 UDF udfd is initialized
05/02 14:38:01.508000 00000085 UDF udfd process exited with status 251, signal 0
05/02 14:38:01.508003 00000085 UDF udfd process restart
05/02 14:38:01.508004 00000085 UDF start to init udfd
05/02 14:38:01.508006 00000085 UDF udfd LD_LIBRARY_PATH: :/usr/lib
05/02 14:38:01.508825 00000085 UDF udfd is initialized
05/02 14:38:01.511966 00000085 UDF udfd process exited with status 251, signal 0
05/02 14:38:01.511971 00000085 UDF udfd process restart
05/02 14:38:01.511972 00000085 UDF start to init udfd
05/02 14:38:01.511974 00000085 UDF udfd LD_LIBRARY_PATH: :/usr/lib
05/02 14:38:01.512815 00000085 UDF udfd is initialized
05/02 14:38:01.515618 00000085 UDF udfd process exited with status 251, signal 0
05/02 14:38:01.515622 00000085 UDF udfd process restart
05/02 14:38:01.515622 00000085 UDF start to init udfd
05/02 14:38:01.515624 00000085 UDF udfd LD_LIBRARY_PATH: :/usr/lib
05/02 14:38:01.516508 00000085 UDF udfd is initialized
05/02 14:38:01.520001 00000085 UDF udfd process exited with status 251, signal 0
05/02 14:38:01.520006 00000085 UDF udfd process restart
```

docker-compose：
```
version: "3"

networks:
  tdengine:

services:
  td1:
    image: tdengine/tdengine:$VERSION
    restart: always
    networks:
      - tdengine
    environment:
      TAOS_FQDN: "td1"
      TAOS_FIRST_EP: "td1"
    volumes:
      - $NODE_DIR/td1/data:/var/lib/taos
      - $NODE_DIR/td1/log:/var/log/taos
  td2:
    image: tdengine/tdengine:$VERSION
    restart: always
    networks:
      - tdengine
    environment:
      TAOS_FQDN: "td2"
      TAOS_FIRST_EP: "td1"
    volumes:
      - $NODE_DIR/td2/data:/var/lib/taos
      - $NODE_DIR/td2/log:/var/log/taos
  td3:
    image: tdengine/tdengine:$VERSION
    restart: always
    networks:
      - tdengine
    environment:
      TAOS_FQDN: "td3"
      TAOS_FIRST_EP: "td1"
    volumes:
      - $NODE_DIR/td3/data:/var/lib/taos
      - $NODE_DIR/td3/log:/var/log/taos
  adapter:
    image: tdengine/tdengine:$VERSION
    restart: always
    networks:
      - tdengine
    entrypoint: "taosadapter"
    environment:
      TAOS_FIRST_EP: "td1"
      TAOS_SECOND_EP: "td2"
    deploy:
      replicas: 4
  nginx:
    image: nginx
    depends_on:
      - adapter
    networks:
      - tdengine
    ports:
      - 6041:6041
      - 6044:6044/udp
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
```
