### ISSUE TITLE
ERROR failed to send status req since Sync leader is unreachable

### ISSUE THREAD

**Issue by itouxin** [taosdata/TDengine#21339]
**Bug Description**
3个tdengine节点的k8s集群中，将所有节点均添加为MNODE，重启任一节点，集群会出现“DND ERROR failed to send status req since Sync leader is unreachable”异常

三个节点的文件存储在三台物理机的/home/taos/data下
k8s yaml如下：
```yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: bigdata
  name: "taosd"
  labels:
    app: "tdengine"
spec:
  ports:
    - name: tcp6030
      protocol: "TCP"
      port: 6030
    - name: tcp6041
      protocol: "TCP"
      port: 6041
  selector:
    app: "tdengine"

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: bigdata
  name: taosd-config
  labels:
    app: "tdengine"
data:
  taos.cfg: |+
    locale en_US.UTF-8
    charset UTF-8
    debugFlag 0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bigdata
  name: taosdata-pv1
  labels:
    app: "tdengine"
spec:
  capacity:
    storage: 10Gi
  local:
    path: /home/taos/data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: bigdata
    name: taosdata-tdengine-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cljs01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bigdata
  name: taosdata-pv2
  labels:
    app: "tdengine"
spec:
  capacity:
    storage: 10Gi
  local:
    path: /home/taos/data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: bigdata
    name: taosdata-tdengine-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cljs02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bigdata
  name: taosdata-pv3
  labels:
    app: "tdengine"
spec:
  capacity:
    storage: 10Gi
  local:
    path: /home/taos/data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: bigdata
    name: taosdata-tdengine-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cljs03

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: bigdata
  name: "tdengine"
  labels:
    app: "tdengine"
spec:
  serviceName: "taosd"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: "tdengine"
  template:
    metadata:
      name: "tdengine"
      labels:
        app: "tdengine"
    spec:
      containers:
      - name: "tdengine"
        image: "tdengine/tdengine:3.0.4.2"
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: tcp6030
            protocol: "TCP"
            containerPort: 6030
          - name: tcp6041
            protocol: "TCP"
            containerPort: 6041
        env:
          # POD_NAME for FQDN config
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # SERVICE_NAME and NAMESPACE for fqdn resolve
          - name: SERVICE_NAME
            value: "taosd"
          - name: STS_NAME
            value: "tdengine"
          - name: STS_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # TZ for timezone settings, we recommend to always set it.
          - name: TZ
            value: "Asia/Shanghai"
          # TAOS_ prefix will configured in taos.cfg, strip prefix and camelCase.
          - name: TAOS_SERVER_PORT
            value: "6030"
          # Must set if you want a cluster.
          - name: TAOS_FIRST_EP
            value: "$(STS_NAME)-0.$(SERVICE_NAME).$(STS_NAMESPACE).svc.cluster.local:$(TAOS_SERVER_PORT)"
          # TAOS_FQND should always be set in k8s env.
          - name: TAOS_FQDN
            value: "$(POD_NAME).$(SERVICE_NAME).$(STS_NAMESPACE).svc.cluster.local"
        volumeMounts:
          - name: taosdata
            mountPath: /var/lib/taos
          - name: taosd-config-volume
            mountPath: /etc/taos/
        readinessProbe:
          exec:
            command:
              - taos-check
          initialDelaySeconds: 5
          timeoutSeconds: 5000
        livenessProbe:
          exec:
            command:
              - taos-check
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: taosd-config-volume
        configMap:
          name: taosd-config
          items:
          - key: taos.cfg
            path: taos.cfg
      nodeSelector:
        region: h3c #h3c集群
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: tdengine
        nodeSelector:
          region: h3c
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
  volumeClaimTemplates:
  - metadata:
      namespace: bigdata
      name: taosdata
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "10Gi"
```
**To Reproduce**
1. 运行tdengine集群
2. 将其他两个节点全部设置为MNODE。`CREATE MNODE ON DNODE 2;CREATE MNODE ON DNODE 3;`
3. 手动重启任意节点。`kubectl delete -n bigdata pod tdengine-1`

**Expected Behavior**
集群会出现“DND ERROR failed to send status req since Sync leader is unreachable”异常

**Screenshots**
节点1截图
![image](https://github.com/taosdata/TDengine/assets/16275395/e639d7ca-dd9b-4228-b9ce-df221a75f2a2)
节点2截图
![image](https://github.com/taosdata/TDengine/assets/16275395/f90da5e6-6a58-458f-af80-9d9dd658976d)
节点3截图
![image](https://github.com/taosdata/TDengine/assets/16275395/df4ecfc4-ab07-40fd-8c00-80d051182432)

**Environment (please complete the following information):**
 - CentOS 7.0 and k8s
 - Memory, CPU, current Disk Space
 - TDengine 3.0.4.0 或者 3.0.4.2

**Additional Context**
