### ISSUE TITLE
query performance issue

### ISSUE THREAD

**Issue by tacnaci** [taosdata/TDengine#24043]
![td](https://github.com/taosdata/TDengine/assets/40619572/66576008-f4f2-487f-82d9-d2a29469ac53)

**Comment by yu285** [comment]
请提供版本号。

**Comment by tacnaci** [comment]
> 请提供版本号。

1. TDengine版本：3.0.6.0
2. 部署方式：docker compose
3. Compose Yaml：
```yaml
version: "3"
services:
  my-tdengine:
    image: tdengine:3.0.6.0
    container_name: my-tdengine
    hostname: my.tdengine
    volumes:
      - "/data/walle/tdengine/data:/var/lib/taos"
      - "/data/walle/tdengine/log:/var/log/taos"
      - "/data/walle/tdengine/taos.cfg:/etc/taos/taos.cfg"
```
4. 建表SQL：
```sql
create stable event (ts timestamp, id nchar(128), name nchar(64), specversion nchar(16), type nchar(128), data nchar(10240), time timestamp) tags (source nchar(128));
```
5. 数据量：86374
