### ISSUE TITLE
使用mybatisPlus整合TDengine，连接方式可以使用REST 连接嘛，我看示例程序用的是原生连接方式。

### ISSUE THREAD

**Issue by yzh20021029** [taosdata/TDengine#25793]
**Bug Description**

**To Reproduce**
2. Type in '....'
3. See error

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.0]
 - Memory, CPU, current Disk Space
 - TDengine Version [e.g. 1.6.1.7]

**Additional Context**

**Comment by trdmm** [comment]
可以, 改下`driver-class-name`和`url`
```
spring:
  datasource:
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://ip:6041/test?charset=UTF-8
    username: root
    password: taosdata
```

但是不知道为啥, url后面加上`batchfetch=true`会导致连接不上...搞了好久才发现这个原因...😢 
> 服务端版本: 3.1.1.0
> taos-jdbcdrive版本: 3.2.11
