### ISSUE TITLE
C UDF udfd process exited with status 254, signal 0

### ISSUE THREAD

**Issue by yuequan1997** [taosdata/TDengine#25963]
**Bug Description**
使用Docker部署3.3.0.3集群，疯狂报：C UDF udfd process exited with status 254, signal 0 日志，不停的在刷

**To Reproduce**

**Expected Behavior**

**Screenshots**
docker-compose logs -f 
```
td-3-1  | 05/29 04:13:21.000954 00000129 C UDF start to init udfd
td-3-1  | 05/29 04:13:21.001038 00000129 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-3-1  | 05/29 04:13:21.011497 00000129 C UDF udfd is initialized
td-3-1  | 05/29 04:13:21.025265 00000129 C UDF udfd process exited with status 254, signal 0
td-3-1  | 05/29 04:13:21.025280 00000129 C UDF udfd process restart
td-3-1  | 05/29 04:13:21.025285 00000129 C UDF start to init udfd
td-3-1  | 05/29 04:13:21.025344 00000129 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-3-1  | 05/29 04:13:21.034120 00000129 C UDF udfd is initialized
td-3-1  | 05/29 04:13:21.162942 00000129 C UDF udfd process exited with status 254, signal 0
td-3-1  | 05/29 04:13:21.162969 00000129 C UDF udfd process restart
td-3-1  | 05/29 04:13:21.162976 00000129 C UDF start to init udfd
td-3-1  | 05/29 04:13:21.163074 00000129 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-3-1  | 05/29 04:13:21.173497 00000129 C UDF udfd is initialized
td-1-1  | 05/29 04:14:27.087970 00000050 C UDF udfd process restart
td-1-1  | 05/29 04:14:27.087978 00000050 C UDF start to init udfd
td-1-1  | 05/29 04:14:27.088076 00000050 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-1-1  | 05/29 04:14:27.101089 00000050 C UDF udfd is initialized
td-1-1  | 05/29 04:14:27.117247 00000050 C UDF udfd process exited with status 254, signal 0
td-1-1  | 05/29 04:14:27.117270 00000050 C UDF udfd process restart
td-1-1  | 05/29 04:14:27.117276 00000050 C UDF start to init udfd
td-1-1  | 05/29 04:14:27.117519 00000050 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-1-1  | 05/29 04:14:27.130606 00000050 C UDF udfd is initialized
td-1-1  | 05/29 04:14:27.143218 00000050 C UDF udfd process exited with status 254, signal 0
td-1-1  | 05/29 04:14:27.143241 00000050 C UDF udfd process restart
td-1-1  | 05/29 04:14:27.143248 00000050 C UDF start to init udfd
td-1-1  | 05/29 04:14:27.143363 00000050 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-1-1  | 05/29 04:14:27.154843 00000050 C UDF udfd is initialized
td-1-1  | 05/29 04:14:27.166486 00000050 C UDF udfd process exited with status 254, signal 0
td-1-1  | 05/29 04:14:27.166503 00000050 C UDF udfd process restart
td-1-1  | 05/29 04:14:27.166506 00000050 C UDF start to init udfd
td-3-1  | 05/29 04:13:21.194447 00000129 C UDF udfd process exited with status 254, signal 0
td-3-1  | 05/29 04:13:21.194541 00000129 C UDF udfd process restart
td-1-1  | 05/29 04:14:27.166559 00000050 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-1-1  | 05/29 04:14:27.176723 00000050 C UDF udfd is initialized
td-3-1  | 05/29 04:13:21.194636 00000129 C UDF start to init udfd
td-3-1  | 05/29 04:13:21.194872 00000129 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-1-1  | 05/29 04:14:27.187471 00000050 C UDF udfd process exited with status 254, signal 0
td-1-1  | 05/29 04:14:27.187502 00000050 C UDF udfd process restart
td-3-1  | 05/29 04:13:21.205669 00000129 C UDF udfd is initialized
td-3-1  | 05/29 04:13:21.221680 00000129 C UDF udfd process exited with status 254, signal 0
td-1-1  | 05/29 04:14:27.187506 00000050 C UDF start to init udfd
td-1-1  | 05/29 04:14:27.187645 00000050 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-3-1  | 05/29 04:13:21.221697 00000129 C UDF udfd process restart
td-3-1  | 05/29 04:13:21.221702 00000129 C UDF start to init udfd
td-1-1  | 05/29 04:14:27.200536 00000050 C UDF udfd is initialized
td-3-1  | 05/29 04:13:21.221769 00000129 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-3-1  | 05/29 04:13:21.231327 00000129 C UDF udfd is initialized
td-1-1  | 05/29 04:14:27.216217 00000050 C UDF udfd process exited with status 254, signal 0
td-1-1  | 05/29 04:14:27.216242 00000050 C UDF udfd process restart
td-3-1  | 05/29 04:13:21.250756 00000129 C UDF udfd process exited with status 254, signal 0
td-1-1  | 05/29 04:14:27.216248 00000050 C UDF start to init udfd
td-3-1  | 05/29 04:13:21.250776 00000129 C UDF udfd process restart
td-1-1  | 05/29 04:14:27.216338 00000050 C UDF udfd LD_LIBRARY_PATH: ::/usr/lib
td-3-1  | 05/29 04:13:21.250780 00000129 C UDF start to init udfd
td-1-1  | 05/29 04:14:27.228001 00000050 C UDF udfd is initialized
```
tail udfdlog.0 -n 50
```
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
==================================================
                new log file                      
==================================================
```

我的docker-compose.yml配置如下：
```yaml
version: "3"
services:
  td-1:
    image: tdengine/tdengine:3.3.0.3
    environment:
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
    ports:
      - "6030:6030"
      - "6041-6049:6041-6049"
      - "6041-6049:6041-6049/udp"
    volumes:
      - ./data/taos/dnode1/data:/var/lib/taos
      - ./data/taos/dnode1/log:/var/log/taos
    networks:
      - tdengine_net
  td-2:
    image: tdengine/tdengine:3.3.0.3
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
    volumes:
      - ./data/taos/dnode2/data:/var/lib/taos
      - ./data/taos/dnode2/log:/var/log/taos
    networks:
      - tdengine_net
  td-3:
    image: tdengine/tdengine:3.3.0.3
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
    volumes:
      - ./data/taos/dnode3/data:/var/lib/taos
      - ./data/taos/dnode3/log:/var/log/taos
    networks:
      - tdengine_net

networks:
  tdengine_net:
    driver: bridge
```

**Environment (please complete the following information):**
 - OS: 龙蜥7.9
 - 8G, 4C, 500G
 - TDengine Version [e.g. 3.3.0.3]

**Additional Context**
