### ISSUE TITLE
tdengine3.0.1.8 docker停止后,再次启动报错?

### ISSUE THREAD

**Issue by becage** [taosdata/TDengine#26384]
**Bug Description**
`docker-compose up -d`首次启动成功,
`docker-compose  down`停止后,
`docker-compose up -d`再启动失败, 删除 `data/tao`文件夹可再次启动，问题是删除后历史数据都没了,应该如何改？

报错信息
```
...
tdengine  | 07/03 02:25:24.361024 00000058 UTL default      pageSizeKB               4
tdengine  | 07/03 02:25:24.361030 00000058 UTL default      totalMemoryKB            65681044
tdengine  | 07/03 02:25:24.361036 00000058 UTL default      os sysname               Linux
tdengine  | 07/03 02:25:24.361042 00000058 UTL default      os nodename              676f470729e8
tdengine  | 07/03 02:25:24.361049 00000058 UTL default      os release               3.10.0-1160.el7.x86_64
tdengine  | 07/03 02:25:24.361055 00000058 UTL default      os version               #1 SMP Mon Oct 19 16:18:59 UTC 2020
tdengine  | 07/03 02:25:24.361061 00000058 UTL default      os machine               x86_64
tdengine  | 07/03 02:25:24.361067 00000058 UTL default      version                  3.0.1.8
tdengine  | 07/03 02:25:24.361073 00000058 UTL default      compatible_version       3.0.0.0
tdengine  | 07/03 02:25:24.361079 00000058 UTL default      gitinfo                  9e47ea605620acab27e84e6280a91db79b744322
tdengine  | 07/03 02:25:24.361086 00000058 UTL default      buildinfo                Built at 2022-11-24 18:16
tdengine  | 07/03 02:25:24.361091 00000058 UTL =================================================================
tdengine  | 07/03 02:25:24.364834 00000058 DND start to init dnode env
tdengine  | 07/03 02:25:24.365135 00000058 DND ERROR dnode:1, localEp 676f470729e8:6030 different from e804782d6db5:6030
tdengine  | 07/03 02:25:24.370240 00000058 DND ERROR localEp 676f470729e8:6030 different with /var/lib/taos//dnode/dnode.json and need reconfigured
tdengine  | 07/03 02:25:24.372938 00000058 DND ERROR failed to read file since success
tdengine  | 07/03 02:25:24.419702 00000058 DND ERROR failed to create dnode since success
tdengine  | 07/03 02:25:24.421390 00000058 DND ERROR failed to init dnode since success
tdengine exited with code 255
```

docker-compose.yml
```
services:
  tdengine:
    image: tdengine/tdengine:3.0.1.8
    container_name: tdengine
    volumes:
      - ./data/taos/log:/var/log/taos
      - ./data/taos/data:/var/lib/taos
    ports:
      - 6040:6040
      - 6041:6041/udp

  redis:
    image: redis
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=redis
    command: redis-server --appendonly yes --requirepass "redis"
    volumes:
      - ./data/redis:/data
```

**Comment by becage** [comment]
`docker-compose.yml` 文件增加节点名称
```
services:
  tdengine:
    image: tdengine/tdengine:3.0.1.8
    container_name: tdengine
    hostname: td3018

```
