### ISSUE TITLE
到底应该用时区utc-8还是utc+8？

### ISSUE THREAD

**Issue by Wuyiz** [taosdata/TDengine#27563]
linux环境下taos.cfg文件中，时区用的是utf-8作为东八区的时区，而不是常见的utc+8或者Asia/Shanghai；然后你们github提供的mybatis-plus的代码示例中，jdbc的url连接参数timezone也是utc-8；

我作为一个开发者，复制了你们的示例代码，在本地运行并尝试插入一条数据，然后再去taos里查询，发现时间错误，根本原因是因为，对于我的本地运行的Java程序来说，utf-8其实是西八区，而在linux部署的tdengine里utf-8是东八区，对于了解不多的人来说很具有迷惑性

```
#linux环境安装的taos.cfg配置文件
# system time zone
timezone                  UTC-8
# system time zone (for windows 10)
timezone              Asia/Shanghai (CST, +0800)
```

```
#你们提供的github示例代码配置连接
spring:
 datasource:
    username: username
    password: password
    url: jdbc:TAOS://127.0.0.1:6030/db_name?charset=UTF-8&locale=en_US.UTF-8&timezone=utf-8
    driver-class-name: com.taosdata.jdbc.TSDBDriver
```
