### ISSUE TITLE
使用 Docker-compose 部署 tdengine:3.3.3.0 集群报 upload to keeper error 错误

### ISSUE THREAD

**Issue by klvchen** [taosdata/TDengine#28602]
**环境**
服务器版本：CentOS Linux release 7.8.2003 (Core)
Dokcer版本：20.10.15
docker-compose 版本： 1.29.1

**docker-compose.yml**
```
version: "3"
services:
  td-1:
    image: tdengine/tdengine:3.3.3.0
    environment:
      TAOS_FQDN: "td-1"
      TAOS_FIRST_EP: "td-1"
    ports:
      - 6041:6041
      - 6030:6030
      - 6060:6060
    volumes:
      - ./data/taosdata-td1:/var/lib/taos
      - ./logs/taoslog-td1:/var/log/taos

  td-2:
    image: tdengine/tdengine:3.3.3.0
    environment:
      TAOS_FQDN: "td-2"
      TAOS_FIRST_EP: "td-1"
    volumes:
      - ./data/taosdata-td2:/var/lib/taos
      - ./logs/taoslog-td2:/var/log/taos

  td-3:
    image: tdengine/tdengine:3.3.3.0
    environment:
      TAOS_FQDN: "td-3"
      TAOS_FIRST_EP: "td-1"
    volumes:
        - ./data/taosdata-td3:/var/lib/taos
        - ./logs/taoslog-td3:/var/log/taos
```

**出现的报错信息**
DB  ERROR QID:0x4000000000000002 latency:37.517439ms, sql:create database if not exists log buffer 64  keep 90  cachemodel 'both'  vgroups 1 , err:Post "http://buildkitsandbox:6041/rest/sql?req_id=4611686018427387906": dial tcp: lookup buildkitsandbox on 127.0.0.11:53: no such host
11/01 02:41:49.518004 00000119 REP ERROR create database log error, msg:Post "http://buildkitsandbox:6041/rest/sql?req_id=4611686018427387906": dial tcp: lookup buildkitsandbox on 127.0.0.11:53: no such host
panic: Post "http://buildkitsandbox:6041/rest/sql?req_id=4611686018427387906": dial tcp: lookup buildkitsandbox on 127.0.0.11:53: no such host
11/01 02:42:15.004684 00000035 MON ERROR upload_id:0x2000000000000100, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
11/01 02:42:15.489452 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:cluster_uptime
11/01 02:42:15.489480 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:dbs_total
11/01 02:42:15.489484 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:tbs_total
11/01 02:42:15.489486 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:stbs_total
11/01 02:42:15.489489 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:vgroups_total
11/01 02:42:15.489492 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:vgroups_alive
11/01 02:42:15.489494 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:vnodes_total
11/01 02:42:15.489496 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:vnodes_alive
11/01 02:42:15.489498 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:mnodes_total
11/01 02:42:15.489501 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:mnodes_alive
11/01 02:42:15.489503 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:connections_total
11/01 02:42:15.489505 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:topics_total
11/01 02:42:15.489507 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:streams_total
11/01 02:42:15.489510 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:dnodes_total
11/01 02:42:15.489512 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:dnodes_alive
11/01 02:42:15.489517 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:grants_expire_time
11/01 02:42:15.489520 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:grants_timeseries_used
11/01 02:42:15.489522 00000082 C UTL ERROR failed to remove metric taosd_cluster_info:grants_timeseries_total
11/01 02:42:15.489807 00000082 C UTL ERROR failed to remove metric taosd_mnodes_info:role
11/01 02:42:15.489842 00000082 C UTL ERROR failed to remove metric taosd_vnodes_info:role
11/01 02:42:30.007021 00000035 MON ERROR upload_id:0x2000000000000200, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
11/01 02:42:45.003677 00000035 MON ERROR upload_id:0x2000000000000300, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
11/01 02:42:45.729900 00000072 C MND succeed to send telemetry report
11/01 02:43:00.006449 00000035 MON ERROR upload_id:0x2000000000000400, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
11/01 02:43:15.008220 00000035 MON ERROR upload_id:0x2000000000000500, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused

![QQ20241101-104303](https://github.com/user-attachments/assets/6a4a0bae-7480-46ca-a0f3-ff9c38bedb8d)

请教一下该如何解决这个报错问题。
