### ISSUE TITLE
运行一段时间后，突然报错 failed to acquite target io.Writer: try create new files too many times

### ISSUE THREAD

**Issue by CxistHans** [taosdata/TDengine#29125]
**Bug Description**
之前安装一路正常，两天后突然报错：
```log
write log error: failed to acquite target io.Writer: try create new files too many times
Failed to fire hook: failed to acquite target io.Writer: try create new files too many times
12/13 03:31:00.005927 00000035 MON ERROR upload_id:0x2000000000095200, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
12/13 03:31:15.004949 00000035 MON ERROR upload_id:0x2000000000095300, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
12/13 03:31:30.005815 00000035 MON ERROR upload_id:0x2000000000095400, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
12/13 03:31:45.006813 00000035 MON ERROR upload_id:0x2000000000095500, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
12/13 03:32:00.006544 00000035 MON ERROR upload_id:0x2000000000095600, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
12/13 03:32:15.006891 00000035 MON ERROR upload_id:0x2000000000095700, upload to keeper error, err:Post "http://127.0.0.1:6043/adapter_report": dial tcp 127.0.0.1:6043: connect: connection refused
```

**To Reproduce**
用dbeaver 连接测试正常，打开表就超时，然后看到报错

**Screenshots**
![849781a71c7b46ef5bf5085e8e2d27a1](https://github.com/user-attachments/assets/55adb462-7d56-431f-a142-053cda8c9565)

**Environment (please complete the following information):**
 - OS: k8s节点应该跟报错无关
 - 资源够用
 - TDengine Version [docker : 3.3.4.8]

**Additional Context**
k8s 部署的，yml:
```yml
kind: StatefulSet
metadata:
  name: tdengine
  namespace: tdengine
spec:
  selector:
    matchLabels:
      app: tdengine
  serviceName: tdengine
  template:
    metadata:
     labels:
       app: tdengine
    spec:
      nodeSelector:
        servicetype: base
      containers:
      - name: tdengine
        image: tdengine:3.3.4.8
        ports:
        - containerPort: 6041
          name: interface
        - containerPort: 6030
          name: taosc
        - containerPort: 6060
          name: explorer
        volumeMounts:
          - name: storage-data
            mountPath: var/lib/taos
          - name: storage-log
            mountPath: /var/log/taos
          - name: tz-config
            mountPath: /etc/localtime
        env:
        - name: TZ
          value: "Asia/Shanghai"
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: storage-data
          persistentVolumeClaim:
            claimName: tdengine-data
        - name: storage-log
          persistentVolumeClaim:
            claimName: tdengine-log

```
nfs 目录:
![image](https://github.com/user-attachments/assets/beb2308a-2695-4281-b75f-268b276391db)
上面还有很多的lock结尾的文件

猜测: 是生成的log权限问题？
