### ISSUE TITLE
docker部署的版本无法进入可视化管理界面

### ISSUE THREAD

**Issue by solekubi** [taosdata/TDengine#30977]
![Image](https://github.com/user-attachments/assets/ef0a7463-5653-4f47-a253-54e327ea633c)

![Image](https://github.com/user-attachments/assets/15b55b34-5f3c-40cc-b8e8-ee42e3a15a50)

docker_compose.yaml 文件如下：
```yaml
services:
  taos:
    image: tdengine/tdengine:3.3.3.0
    container_name: taos
    restart: unless-stopped
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "6030:6030"
      - "6041:6041"
      - "6043-6060:6043-6060"
      - "6043-6060:6043-6060/udp"
    volumes:
      - ~/logs/taos:/var/log/taos
      - ~/data/taos:/var/lib/taos
````
