### ISSUE TITLE
localEp is different from taos:6030 

### ISSUE THREAD

**Issue by mm-e1** [taosdata/TDengine#5398]
I am getting an error when running tdengine/tdengine-aarch64:2.0.16.0 docker container on a raspberry pi 4:

Docker Compose:

```
version: '2.1'

services:

  taos:
    image: tdengine/tdengine-aarch64:2.0.16.0
    restart: always
    container_name: taos
    volumes:
       - "taos-data:/var/lib/taos"
       - "taos-data:/var/log/taos"
    ports:
      - 6020:6020
      - 6030:6030
      - 6035:6035
      - 6030-6039:6030-6039/udp

networks:
    default:
        driver: bridge

volumes:
  taos-data: {}
  
```    

Error:
```
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.697925 0x7f870b8510 DND step:dnode-globalcfg is initialized
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.703450 0x7f870b8510 TFS disk /var/lib/taos is mounted to tier level 0 id 0
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.703713 0x7f870b8510 DND dnode storage is initialized at /var/lib/taos/dnode
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.703757 0x7f870b8510 DND step:dnode-storage is initialized
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.703895 0x7f870b8510 DND read file /var/lib/taos/dnode/dnodeCfg.json successed
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.703946 0x7f870b8510 DND dnodeId is set to 1, clusterId is set to 25bc46da-ffb4-446e-aa17-4615ccdf50b3
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.713207 0x7f870b8510 DND successed to write /var/lib/taos/dnode/dnodeCfg.json
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.713303 0x7f870b8510 DND dnode cfg is initialized
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.713332 0x7f870b8510 DND step:dnode-cfg is initialized
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.713524 0x7f870b8510 DND read file /var/lib/taos/dnode/dnodeEps.json successed
[Logs]    [3/9/2021, 10:31:41 PM] [taos] 03/10 03:31:41.713623 0x7f870b8510 DND ERROR dnode:1, localEp is different from taos:6030 in dnodeEps.json and need reconfigured
```
