### ISSUE TITLE
How to specify the database used in docker-compose ? like postgres influxDB.

### ISSUE THREAD

**Issue by richwxd** [taosdata/TDengine#8294]
在tdengine的docker-compose里如何实现如下的配置？
比如postgres：
```yaml
ports:
      - "5432:5432"
    privileged: true  #解决权限
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      TZ: Asia/Shanghai
```

influx:
```yaml
environment:
      - INFLUXDB_DB=mydb1
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpwd
      - INFLUXDB_USER=mydb1user
      - INFLUXDB_USER_PASSWORD=mydb1pwd
```

**Comment by luodaoyi** [comment]
```
version: '2'

services:
  dashboard: 
    depends_on:
      - db
    image: ghcr.io/xxxx:latest
    restart: always
    environment:
      DATABASE_URL: tdengine://root:taosdata@db:6041/xxx
    ports:
      - "127.0.0.1:8180:80"
 
  db:
    image: tdengine/tdengine:latest 
    restart: always
    volumes:
     - "./data/taos/log:/var/log/taos"
     - "./data/taos/lib:/var/lib/taos"
     - "./data/taos/etc:/etc/taos"
  
```

这样的可以吗
